apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: argocd
spec:
  serviceAccountName: argocd-server
  restartPolicy: Never
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - sh
      - -c
      - |
        curl -sSk -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc/api/v1/namespaces/argocd/configmaps/argocd-cm && sleep 5
